### ISSUE TITLE
Documentation for "Node.js http request object"

### ISSUE THREAD

**Issue by denilsonsa** [nuxt/docs#1670]
### What problem does this feature solve?

Short version
--------

Please add links pointing to the proper documentation of `req` and `res` objects.

I don't do it myself (and send the PR) because I'm not familiar with this project and I don't know what is the correct documentation.

Long version
---------

1. Start writing an application using [NuxtJS](https://nuxtjs.org/).
2. Decide you want to write a custom *Server Middleware* in NuxtJS.
3. Find the [official NuxtJS documentation](https://nuxtjs.org/api/configuration-servermiddleware#the-servermiddleware-property). It points to [Connect Docs](https://github.com/senchalabs/connect#appusefn/) (I've created [an issue over there]( https://github.com/senchalabs/connect/issues/1122) as well).
4. Observe the documentation says:
          // req is the Node.js http request object
          // res is the Node.js http response object
5. Fumble and waste time trying to search the documentation for Node.js http request/response objects.

Expectation: To have a link pointing to the right documentation.

Reality: No link, so now I have to search for it, and hope the documentation I'm reading is the correct one.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/docs/issues/c228">#c228</a>)</em></sub></div>

**Comment by denilsonsa** [comment]
* [NuxtJS uses `connect` as the app.](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/server.js#L34)
* [NuxtJS uses either `http` or `https` server from Node.js.](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/listener.js#L65)
* [NuxtJS passes the `connect` app as the `requestListener` parameter of `createServer`.](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/listener.js#L67)
* There doesn't seem to be any option `IncomingMessage` or `ServerResponse` in [connect](https://github.com/senchalabs/connect/blob/bd0d23d/index.js), in [NuxtJS listener](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/listener.js), or in [NuxtJS server](https://github.com/nuxt/nuxt.js/blob/a87f5dde6ad5c6a87553ac30e1eb4f462ea7657f/packages/server/src/server.js); thus I believe the `req` and `res` will be the ones defined/documented at [http.createServer](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener):
    * [`http.IncomingMessage`](https://nodejs.org/api/http.html#http_class_http_incomingmessage)
    * [`http.ServerResponse`](https://nodejs.org/api/http.html#http_class_http_serverresponse)

**Comment by kevin2y** [comment]
i need it too!

when i add this to nuxt.config.js

serverMiddleware: [   
    { path: '/list', handler: '~/server/listapi' }
  ]

and my listapi.js is 

export default function (req, res, next) {    
    res.end('{ "name": "to witty" }');;
    next()
}

webbrower can receive info and act good,but server report error:

(node:8384) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at sendResponse (D:\web\nuxt-first\node_modules\@nuxt\server\dist\server.js:295:9)
    at errorMiddleware (D:\web\nuxt-first\node_modules\@nuxt\server\dist\server.js:356:5)
