### ISSUE TITLE
How to add dependency ~router?

### ISSUE THREAD

**Issue by Tim86** [nuxt/docs#195]
I'm trying to add google analytics with the method described at https://github.com/nuxt/docs/blob/master/en/faq/google-analytics.md but get the following error when running ```npm run dev```. How do I solve this?
```
This dependency was not found:

* ~router in ./plugins/ga.js

To install it, you can run: npm install --save ~router
Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1315:14)
    at listenInCluster (net.js:1363:12)
    at GetAddrInfoReqWrap.doListen (net.js:1489:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)
```

**Comment by pi0** [comment]
Hi! Please official [google-analytics](https://github.com/nuxt-community/modules/tree/master/modules/google-analytics) module for rcs. Sorry for inconviences during lack of docs. We are heavily working to update them faster.
