### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by jordanranson** [nuxt/docs#311]
When I follow the setup instructions (npm install, npm run dev) I get the following error when I run the dev command:

```
/Users/jordanranson/projects/docs/api.js:37
async function getReleases () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by pi0** [comment]
Hey. Please simply upgrade Node.js to 8.x :)

**Comment by jordanranson** [comment]
Oh, sorry. Must have skimmed over that in the README! It's very obvious now that I look at it.
