### ISSUE TITLE
Function which returns a Promise~ import axios from 'axios' error happened

### ISSUE THREAD

**Issue by adon988** [nuxt/docs#42]
When I Following the step of **The generate Property**
https://nuxtjs.org/api/configuration-generate/

because I have dynamic params, so I try to following the step of  **Function which returns a Promise**

But error happened!!!

nuxt.config.js
```
...
import axios from 'axios'

module.exports = {
  generate: {
    routeParams: {
...
```
Error:@@
```
$ npm run generate

> nuxt@1.0.0 generate C:\xampp\htdocs\adam_lab\vue\nuxt
> nuxt generate

C:\xampp\htdocs\adam_lab\vue\nuxt\nuxt.config.js:1
(function (exports, require, module, __filename, __dirname) { import axios from 'axios'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\adam_lab\vue\nuxt\node_modules\nuxt\bin\nuxt-generate:15:13)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Adam\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "generate"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! nuxt@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuxt@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nuxt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nuxt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nuxt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\adam_lab\vue\nuxt\npm-debug.log

```
What's happened ~ORZ

**Comment by Atinux** [comment]
You cannot use the `import` method in `nuxt.config.js` since it's node.js and it does not support `import` yet.

You should do `const axios = require('axios')`

**Comment by adon988** [comment]
Thanks @Atinux  ~ It's work ~~~
